TELEGRAM_BOT_TOKEN = "8813434919:AAHytB4BlyZ_NgwSvprzpEXBrNUXhLPdGYk"

[postgres]
host = "db.zufalogivvjkejxewvnb.supabase.co"
port = 5432
database = "postgres"
user = "postgres"
password = "SpU,@w79.T?A*k"